#!/bin/sh

[ `xinput | grep "Touchpad" | awk '{ print $6 }' | sed 's/\id=//g' | xargs -r xinput --list-props | grep "Device Enabled" | awk '{ print $4}'` = "1" ] &&	xinput | grep "Touchpad" | awk '{ print $6 }' | sed 's/\id=//g' | xargs -r xinput disable || xinput | grep "Touchpad" | awk '{ print $6 }' | sed 's/\id=//g' | xargs -r xinput enable
